### ISSUE TITLE
[Suggestion] Make links in descriptions convert to clickable links automatically.

### ISSUE THREAD

**Issue by schlid** [LeMinaw/skywarehouse#11]
Make links entered in the image description clickable.

This would be useful for links to twitch clips, galleries for more images and so on.

**Comment by schlid** [comment]
http://www.skywa.re/blueprint/kite-shuttle

Example.

**Comment by LeMinaw** [comment]
I think we have have two options here : make links clickable automatically, or add [markdown](https://www.markdownguide.org/cheat-sheet) support in description.

The first is easier for the user but less permissive, the second allows a lot more but is less obvious. Whtat's your opinion?

A special field for imgur album / yt or twitch id would be cool too, I suppose.

**Comment by schlid** [comment]
I think due to the frequency of people wanting to have more than one image, auto detection might be the better choice, with special detection for imgur, yt and twitch and other popular media sites to embed?

That's my two cents - although markdown is pretty easy to use, it's not everyone's first choice and it would give peace of mind knowing the links would work regardless of where they are in the description and how they are formatted.

**Comment by LeMinaw** [comment]
Links in description are clickable since 65f73a415f11a929aa81d2ed09d8caeb2fb5211f. Comments and bios do too since 0a2a3a938cf3b0f717a3440301dfbec082b66f26.
