### ISSUE TITLE
[BUG] Can't Create an Account

### ISSUE THREAD

**Issue by Aiwii** [LeMinaw/skywarehouse#16]
Whenever I attempt to create an account I get "ERROR 500"

![image](https://user-images.githubusercontent.com/53021785/69831553-14110a00-11e7-11ea-81f9-7f74a7006967.png)

**Comment by LeMinaw** [comment]
Thanks for reporting this. It shoud be fixed now (060d7a09d12beddcb344f2b19e58b4622286b76a).
