### ISSUE TITLE
[SUGGESTION] Image max dimensions

### ISSUE THREAD

**Issue by schlid** [LeMinaw/skywarehouse#5]
![image](https://user-images.githubusercontent.com/31857052/44594716-ef95d900-a7be-11e8-8da6-121a9d56cb39.png)

Not sure if you've already implemented this after you uploaded your dragon ship, but if all the images were of equal sizes, and titles would get shortened with elipses, for example "The Core Ship (Extremely laggy shell)" would shorten to "The Core Ship (Extremely..." to keep it onto one line, just making every ship "card" have the same dimensions would give the page a much cleaner appearance, especially when it's populated.

**Comment by LeMinaw** [comment]
I added truncation for titles in bef0e7286b1f0f84f8957d630db63d0b54caa864. I'll dive a bit more on this soon.

**Comment by LeMinaw** [comment]
New BP cards layout (08f9606533c9dc77114dc2819d39f04fdb2601ff) makes this obsolete.
