### ISSUE TITLE
[SUGGESTION] move the button to filter hovercrafts next to mechs for consistency.

### ISSUE THREAD

**Issue by schlid** [LeMinaw/skywarehouse#6]
![image](https://user-images.githubusercontent.com/31857052/44596816-81084980-a7c5-11e8-8353-052f2662e4a3.png)

Ergonomically, this would make the most sense as these are the 3 main types of vehicle in the game, with the other two tabs being subsections of builds or neat things you could slot into a project. It may also be worth adding a category filter for "stations" too.

**Comment by LeMinaw** [comment]
fixed in cfb2469f8cf3b36ba892aab186afe0670ccf0da0
I will also add the new category.
